oneup_flysystem:
    adapters:
        public_uploads_adater:
            local:
                directory: '%kernel.project_dir%/public/%uploads_dir_name%'
        private_uploads_adater:
            local:
                directory: '%kernel.project_dir%/var/uploads'
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adater
        private_uploads_filesystem:
            adapter: private_uploads_adater